winget uninstall --force "ARP\Machine\X64\OneDriveSetup.exe"
winget uninstall --force "MSIX\Microsoft.OneDriveSync_26095.519.3.0_neutral__8wekyb3d8bbwe"
winget uninstall --force "Microsoft.OneDrive"
winget uninstall --force "Microsoft Update Health Tools"
winget uninstall --force "ARP\Machine\X86\Microsoft Copilot"
winget uninstall --force "Microsoft Search in Bing"
winget uninstall --force "Microsoft Notícias"
winget uninstall --force "News"
winget uninstall --force "Notícias"
winget uninstall --force "Microsoft Bing"
winget uninstall --force "MSN Clima"
winget uninstall --force "Dicas da Microsoft"
winget uninstall --force "Xbox"
winget uninstall --force "Microsoft 365 Copilot"
winget uninstall --force "Solitaire & Casual Games"
winget uninstall --force "Notas Autoadesivas da Microsoft"
winget uninstall --force "Aplicativo Start Experiences"
winget uninstall --force "Vincular ao Celular"
winget uninstall --force "Assistência Rápida"
winget uninstall --force "One Drive"
winget uninstall --force "Skype"
winget uninstall --force "Hub de Comentários"
winget uninstall --force "Xbox TCUI"
winget uninstall --force "Xbox Console Companion"
winget uninstall --force "Xbox Game Bar Plugin"
winget uninstall --force "Xbox Identity Provider"
winget uninstall --force "Xbox Game Speech Window"
